### ISSUE TITLE
Getting ERROR not well-formed (invalid token)

### ISSUE THREAD

**Issue by EvanLovely** [robwalton/alfred-ulysses-workflow#10]
I'm getting `workflow.py:2243 ERROR    not well-formed (invalid token): line 1, column 9` after a fresh install of v1.0.3 of your workflow on Ulysses 13 (v42335) that was released last week. I attempted running `uf`, but I'm pretty sure it happens on all commands.

Thanks! Here's the full output from the Alfred debug window:

```
Starting debug for 'Ulysses'

[2018-06-06 10:45:24][ERROR: input.scriptfilter] Code 1: 10:45:24 workflow.py:2225 DEBUG    Workflow version : 1.0.3
10:45:24 workflow.py:1628 DEBUG    Reading settings from `/Users/Evan/Library/Application Support/Alfred 3/Workflow Data/com.github.robwalton.alfred-ulysses-workflow/settings.json` ...
10:45:24 workflow.py:2514 DEBUG    Update check not due
10:45:24 ulysses_items.py:59 INFO     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
10:45:24 ulysses_items.py:60 INFO     ulysses_items.main(wf): args = 
Namespace(kind='all', limit_scope_dir=None, query=u'', search_content=True, search_ulysses_path=False)
10:45:24 ulysses_items.py:61 INFO     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
10:45:24 workflow.py:1859 DEBUG    Loading cached data from : /Users/Evan/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.github.robwalton.alfred-ulysses-workflow/__workflow_update_status.cpickle
10:45:24 workflow.py:2444 DEBUG    update_data : {u'available': False}
10:45:24 ulysses_items.py:86 INFO     Added iCloud items from '/Users/Evan/Library/Mobile Documents/X5AZV975AG~com~soulmen~ulysses3/Documents/Library/Groups-ulgroup'
10:45:24 workflow.py:2243 ERROR    not well-formed (invalid token): line 1, column 9
Traceback (most recent call last):
  File "/Users/Evan/Dropbox/settings/Alfred.alfredpreferences/workflows/user.workflow.A5704485-717B-40BA-83C7-A0F75BCDDF25/workflow/workflow.py", line 2236, in run
    func(self)
  File "ulysses_items.py", line 89, in main
    include_sheets)
  File "ulysses_items.py", line 149, in parse_ulysses_for_groups_and_sheets
    groups_tree = parse_ulysses.create_tree(root_dir, None)
  File "/Users/Evan/Dropbox/settings/Alfred.alfredpreferences/workflows/user.workflow.A5704485-717B-40BA-83C7-A0F75BCDDF25/parse_ulysses.py", line 126, in create_tree
    group = Group(rootgroupdir, parent_group)
  File "/Users/Evan/Dropbox/settings/Alfred.alfredpreferences/workflows/user.workflow.A5704485-717B-40BA-83C7-A0F75BCDDF25/parse_ulysses.py", line 62, in __init__
    self.name = self.title = self._get_group_name(dirpath)
  File "/Users/Evan/Dropbox/settings/Alfred.alfredpreferences/workflows/user.workflow.A5704485-717B-40BA-83C7-A0F75BCDDF25/parse_ulysses.py", line 69, in _get_group_name
    return plistlib.readPlist(join(self.dirpath, 'Info.ulgroup'))['displayName']
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 78, in readPlist
    rootObject = p.parse(pathOrFile)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 406, in parse
    parser.ParseFile(fileobj)
ExpatError: not well-formed (invalid token): line 1, column 9
10:45:24 workflow.py:2246 INFO     For assistance, see: https://github.com/robwalton/alfred-ulysses-workflow
10:45:24 workflow.py:2267 DEBUG    Workflow finished in 0.030 seconds.
```

**Comment by daya0576** [comment]
Same error. 
```
Starting debug for 'Ulysses'

[2018-06-07 14:29:46][ERROR: input.scriptfilter] Code 1: 14:29:46 workflow.py:2225 DEBUG    Workflow version : 1.0.3
14:29:46 workflow.py:1628 DEBUG    Reading settings from `/Users/henry/Library/Application Support/Alfred 3/Workflow Data/com.github.robwalton.alfred-ulysses-workflow/settings.json` ...
14:29:46 workflow.py:2514 DEBUG    Update check not due
14:29:46 ulysses_items.py:59 INFO     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
14:29:46 ulysses_items.py:60 INFO     ulysses_items.main(wf): args = 
Namespace(kind='all', limit_scope_dir=None, query=u'', search_content=False, search_ulysses_path=True)
14:29:46 ulysses_items.py:61 INFO     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
14:29:46 workflow.py:1859 DEBUG    Loading cached data from : /Users/henry/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.github.robwalton.alfred-ulysses-workflow/__workflow_update_status.cpickle
14:29:46 workflow.py:2444 DEBUG    update_data : {u'available': False}
14:29:46 ulysses_items.py:86 INFO     Added iCloud items from '/Users/henry/Library/Mobile Documents/X5AZV975AG~com~soulmen~ulysses3/Documents/Library/Groups-ulgroup'
14:29:46 workflow.py:2243 ERROR    not well-formed (invalid token): line 1, column 9
Traceback (most recent call last):
  File "/Users/henry/Library/Mobile Documents/com~apple~CloudDocs/Alfred.alfredpreferences/workflows/user.workflow.EA5A21D9-08AA-4815-AB3F-336D2E775945/workflow/workflow.py", line 2236, in run
    func(self)
  File "ulysses_items.py", line 89, in main
    include_sheets)
  File "ulysses_items.py", line 149, in parse_ulysses_for_groups_and_sheets
    groups_tree = parse_ulysses.create_tree(root_dir, None)
  File "/Users/henry/Library/Mobile Documents/com~apple~CloudDocs/Alfred.alfredpreferences/workflows/user.workflow.EA5A21D9-08AA-4815-AB3F-336D2E775945/parse_ulysses.py", line 126, in create_tree
    group = Group(rootgroupdir, parent_group)
  File "/Users/henry/Library/Mobile Documents/com~apple~CloudDocs/Alfred.alfredpreferences/workflows/user.workflow.EA5A21D9-08AA-4815-AB3F-336D2E775945/parse_ulysses.py", line 62, in __init__
    self.name = self.title = self._get_group_name(dirpath)
  File "/Users/henry/Library/Mobile Documents/com~apple~CloudDocs/Alfred.alfredpreferences/workflows/user.workflow.EA5A21D9-08AA-4815-AB3F-336D2E775945/parse_ulysses.py", line 69, in _get_group_name
    return plistlib.readPlist(join(self.dirpath, 'Info.ulgroup'))['displayName']
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 78, in readPlist
    rootObject = p.parse(pathOrFile)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 406, in parse
    parser.ParseFile(fileobj)
ExpatError: not well-formed (invalid token): line 1, column 9
14:29:46 workflow.py:2246 INFO     For assistance, see: https://github.com/robwalton/alfred-ulysses-workflow
14:29:46 workflow.py:2267 DEBUG    Workflow finished in 0.044 seconds.
```

**Comment by robwalton** [comment]
Hi @EvanLovely and @daya0576, thanks for the error reports. I've released [v.1.0.4](https://github.com/robwalton/alfred-ulysses-workflow/releases/tag/v.1.0.4) to GitHub. Please let me know if it all works as expected and I'll push to packal.
