### ISSUE TITLE
Ulysses new sheet still not working

### ISSUE THREAD

**Issue by tonyl08** [robwalton/alfred-ulysses-workflow#12]

**Comment by tonyl08** [comment]
Hi Rob -- I'm still getting the following error in Ulysses v15.2. (See below). Any fix available? Appreciate all that you do. (I've dropped in 'ME' for my user folder in the below)

Starting debug for 'Ulysses'

**[2019-03-23 16:31:45][ERROR: input.scriptfilter] Code 1: 16:31:45 workflow.py:2247 DEBUG    ---------- Ulysses (1.0.4) ----------**

16:31:45 workflow.py:1657 DEBUG    reading settings from /Users/ME/Library/Application Support/Alfred 3/Workflow Data/com.github.robwalton.alfred-ulysses-workflow/settings.json
16:31:45 workflow.py:2526 INFO     checking for update ...
16:31:45 background.py:233 DEBUG    [__workflow_update_check] command cached: /Users/ME/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.github.robwalton.alfred-ulysses-workflow/__workflow_update_check.argcache
16:31:45 background.py:237 DEBUG    [__workflow_update_check] passing job to background runner: [u'/usr/bin/python', '/Users/ME/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.BC26EDB6-06E2-4C17-BF4B-07064C1719D7/workflow/background.pyc', u'__workflow_update_check']
16:31:45 workflow.py:2247 DEBUG    ---------- Ulysses (1.0.4) ----------
16:31:45 background.py:243 DEBUG    [__workflow_update_check] background job started
16:31:45 ulysses_items.py:59 INFO     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
16:31:45 ulysses_items.py:60 INFO     ulysses_items.main(wf): args = 
Namespace(kind='group', limit_scope_dir=None, query=u'', search_content=False, search_ulysses_path=True)
16:31:45 ulysses_items.py:61 INFO     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
16:31:45 workflow.py:2461 DEBUG    update_data: None
16:31:45 ulysses_items.py:86 INFO     Added iCloud items from '/Users/ME/Library/Mobile Documents/X5AZV975AG~com~soulmen~ulysses3/Documents/Library/Groups-ulgroup'
16:31:45 ulysses_items.py:86 INFO     Added iCloud Inbox items from '/Users/ME/Library/Mobile Documents/X5AZV975AG~com~soulmen~ulysses3/Documents/Library/Unfiled-ulgroup'
16:31:45 workflow.py:2266 ERROR    
Traceback (most recent call last):
  File "/Users/ME/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.BC26EDB6-06E2-4C17-BF4B-07064C1719D7/workflow/workflow.py", line 2259, in run
    func(self)
  File "ulysses_items.py", line 89, in main
    include_sheets)
  File "ulysses_items.py", line 149, in parse_ulysses_for_groups_and_sheets
    groups_tree = parse_ulysses.create_tree(root_dir, None)
  File "/Users/ME/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.BC26EDB6-06E2-4C17-BF4B-07064C1719D7/parse_ulysses.py", line 126, in create_tree
    assert 'Info.ulgroup' in filelist
AssertionError
16:31:45 workflow.py:2268 INFO     for assistance, see: https://github.com/robwalton/alfred-ulysses-workflow
16:31:45 workflow.py:2289 DEBUG    ---------- finished in 0.199s ----------
